// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqZq16SWH5EcD1Lcyi0FkTtKsWgmHqdXI',
    appId: '1:123358633532:android:830113ec4cf139fc5b6d39',
    messagingSenderId: '123358633532',
    projectId: 'todo-proj-3a4cd',
    storageBucket: 'todo-proj-3a4cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJcR_zJ8iR33Y6xZ8eSF7qwXmFHzZynZY',
    appId: '1:123358633532:ios:be7dabaeb72fb8655b6d39',
    messagingSenderId: '123358633532',
    projectId: 'todo-proj-3a4cd',
    storageBucket: 'todo-proj-3a4cd.firebasestorage.app',
    androidClientId: '123358633532-2qfbqm82g9nmqnol289ee9oo6k77fi2s.apps.googleusercontent.com',
    iosClientId: '123358633532-urgt4uh61p58hclnj0d5tg55dv71fmvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
